### PR TITLE
Update gitsign 0.3.1

### PR DESCRIPTION
**Pull request by wlynch**
#### Summary

Update gitsign 0.3.1 - https://github.com/sigstore/gitsign/releases/tag/v0.3.1

#### Release Note

Update gitsign 0.3.1 - https://github.com/sigstore/gitsign/releases/tag/v0.3.1

### CODE REVIEW

**Review by cpanato — CHANGES_REQUESTED** [review]
can you update https://github.com/sigstore/homebrew-tap/blob/main/Formula/gitsign-credential-cache.rb as well?

**Comment by wlynch** [comment]
Always forget to do that 🙃 

Done!

**Comment by cpanato** [comment]
checking what is going on with ci

**Comment by cpanato** [comment]
releated to https://github.com/actions/runner-images/issues/6283

will check a workaround

**Comment by cpanato** [comment]
this fixes: https://github.com/sigstore/homebrew-tap/pull/70

**Review by cpanato — CHANGES_REQUESTED** [review]
need to bump the version in Formula/gitsign-credential-cache.rb :)

**Review by cpanato — APPROVED** [review]
thank you! <3

**Pull request merged**
